//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resrvation
    {
        public int Id { get; set; }
        public string car_name_ { get; set; }
        public string car_number_plate_ { get; set; }
        public string person_name { get; set; }
        public string person_email { get; set; }
        public bool long_time { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime finish_date { get; set; }
    }
}
